### ISSUE TITLE
Benchmarking msgf+

### ISSUE THREAD

**Issue by anubhav0fnu** [microbiomedata/metaPro#10]

**Comment by ssarrafan** [comment]
Adding to September's sprint per Slack chat with @anubhav0fnu

**Comment by ssarrafan** [comment]
@anubhav0fnu should this issue be closed, moved to the backlog or moved to the October sprint?

**Comment by anubhav0fnu** [comment]
It will be closed on sep 30.

**Comment by ssarrafan** [comment]
> It will be closed on sep 30.

Sounds good. Thanks @anubhav0fnu

**Comment by anubhav0fnu** [comment]
It's completed @ssarrafan.
