### ISSUE TITLE
adding splitFasta logic to handle Fastas > 1gb in size.

### ISSUE THREAD

**Issue by anubhav0fnu** [microbiomedata/metaPro#11]

**Comment by ssarrafan** [comment]
Adding this to the October sprint per Slack chat with @anubhav0fnu

**Comment by anubhav0fnu** [comment]
add split-fasta logic
1. python codebase
2. WDL

**Comment by ssarrafan** [comment]
Planned for Nov and Dec sprints per @anubhav0fnu

**Comment by ssarrafan** [comment]
Per @anubhav0fnu moving this to the backlog
#11 is half done, and half would take time so we can put that in backlog for now.
