### ISSUE TITLE
test and process spruce dataset on pnnl-MSC(Tahoma).

### ISSUE THREAD

**Issue by anubhav0fnu** [microbiomedata/metaPro#16]

**Comment by anubhav0fnu** [comment]
[tahoma](https://www.emsl.pnnl.gov/MSC/UserGuide/tahoma/tahoma_overview.html)

**Comment by anubhav0fnu** [comment]
things to do!
- test run of MetaPro on Tahoma.
- Process 
  - []  Spruce dataset 
  - []  Prosser uniref.
  - [X]  update stegen 
  
- add documentation: "How to process a new dataset using MetaPro on Tahoma"
- collect stats for newer runs (disk access, memory, N/w bandwidth, cpu time) form

**Comment by ssarrafan** [comment]
Moving to November to complete per plan from @anubhav0fnu 

https://github.com/microbiomedata/metaPro/issues/16 run from Oct end & will be finished by Nov sprint.

**Comment by ssarrafan** [comment]
Moving to December sprint per @anubhav0fnu via Slack

**Comment by ssarrafan** [comment]
Heard from Yuri that Anubhav is out till January so I am moving this to the January sprint. @anubhav0fnu if you have any updates on this please add to the comments.

**Comment by ssarrafan** [comment]
@anubhav0fnu today we had mid-sprint check-in. I'm following up to see if you have any blockers or need any help with this GitHub issue.  Please let me know.  Thanks!

**Comment by ssarrafan** [comment]
@anubhav0fnu any update on this issue?

**Comment by anubhav0fnu** [comment]
> @anubhav0fnu any update on this issue?

- [X] test run of MetaPro on Tahoma.

Process:
- [X] Spruce dataset
- [X] update stegen
- [X] add documentation: "How to process a new dataset using MetaPro on Tahoma"
- [ ] Prosser uniref.
- [ ] collect stats for newer runs (disk access, memory, N/w bandwidth, cpu time) form
