### ISSUE TITLE
metapro WDL bug fixing and enhancement.

### ISSUE THREAD

**Issue by anubhav0fnu** [microbiomedata/metaPro#17]
Enhancement:
- add logic to `main.wdl` to run the workflow for a list of datasets. 
- adding start-time, end-time, and execution-time logic to WDL 
- Testing the `meta-collection.wdl` 
Bug fixing:
- msgf task is dumping outfile in a `input` directory vs `execution` directory.

**Comment by ssarrafan** [comment]
Added to Nov sprint per Slack message from @anubhav0fnu

**Comment by ssarrafan** [comment]
@anubhav0fnu reported this will be completed this sprint, by tomorrow.

**Comment by ssarrafan** [comment]
@anubhav0fnu I am moving this to closed per our Slack check. Please add details of the work to this issue. I just need to close the November sprint. Thanks!
