### ISSUE TITLE
process Prosser uniref dataset.

### ISSUE THREAD

**Issue by anubhav0fnu** [microbiomedata/metaPro#19]

**Comment by ssarrafan** [comment]
@anubhav0fnu it's mid-sprint time so I'm just checking to see if you think you will be able to finish this issue in March?  Are you blocked by anything? Do you need help with anything?

**Comment by ssarrafan** [comment]
Checked with @pdpiehowski and he said this is complete. Closing this issue.

FYI grant.fujimoto@pnnl.gov
