### ISSUE TITLE
 Benchmarking2.0: collect additional stats for newer runs (disk access, memory, N/w bandwidth, cpu time).

### ISSUE THREAD

**Issue by anubhav0fnu** [microbiomedata/metaPro#20]

**Comment by ssarrafan** [comment]
@anubhav0fnu it's mid-sprint time so I'm just checking to see if you think you will be able to finish this issue in March?  Are you blocked by anything? Do you need help with anything?

**Comment by ssarrafan** [comment]
@pdpiehowski said to re-assign this to Grant. I will move this to April and re-assign to Grant as soon as he joins the GH org.  Invite sent earlier today.

**Comment by ssarrafan** [comment]
@pdpiehowski said to re-assign this to @Grant.Fujimoto@pnnl.gov.  Will move to the April sprint and re-assign when Grant joins GH.

**Comment by ssarrafan** [comment]
Removing from the sprint.  @pdpiehowski and @GrantFujimoto let me know if you plan to work on this in May. Adding the backlog label for now.

**Comment by GrantFujimoto** [comment]
Have current pipeline building and running a testing set of data with associated run times and other metrics. Working on expanding the test set as well as getting more in depth timing and memory metrics.

**Comment by ssarrafan** [comment]
Moving to new sprint, @GrantFujimoto let me know if you're not working on this currently

**Comment by ssarrafan** [comment]
@GrantFujimoto still testing?  Should this issue continue to be active in the next sprint?

**Comment by pdpiehowski** [comment]
The benchmarking is now completed and the decided upon parameters are now implemented in the pipeline.
