### ISSUE TITLE
Preparation Metadata: Proteomics

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/metaPro#21]
- [x]  Identify metadata components that need captured at PNNL (what isn't captured by DMS) (August)
- [ ]  Identify metadata components captured by DMS that are required when data is received from other institutions
- [x]  Generate metadata template (September)
- [ ]  Check & confirm missing components once template and example are complete (@SamuelPurvine , @pdpiehowski ) (October)

**Comment by ssarrafan** [comment]
Moving to the October sprint per Slack message from Montana

**Comment by ssarrafan** [comment]
Moving to the November sprint per Slack message from Montana

**Comment by ssarrafan** [comment]
Adding backlog label and removing from sprints per slack message from @mslarae13 

FYI @SamuelPurvine

**Comment by ssarrafan** [comment]
@mslarae13 @SamuelPurvine should this issue remain open and in the backlog?  Or can I close it?

**Comment by ssarrafan** [comment]
@mslarae13 @SamuelPurvine this one hasn't been updated in over a year. I'll close this one but let me know if you'd still like to work on this specific issue.
