### ISSUE TITLE
QA Benchmark specification

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaPro#26]
This issue is for QA of the metaPro pipeline benchmarking.

To confirm the proper operation of the completed metaPro pipeline we need to validate it against an example dataset processed at PNNL using best practice.  We will identify an LC-MS/MS dataset and metagenome from the NMDC and process using the established approach to create a benchmark dataset.
Dataset will be chosen from those already in NMDC, and the metagenome of sufficient size to utilize all features of the pipeline.  Deliverable will be peptide and protein results files that can be directly compared to metaPro pipeline output.
This output will be used by the metaPro team to validate pipeline and will be put on GitHub for use by others installing the pipeline. This work will be completed in this sprint.

**Comment by ssarrafan** [comment]
Hi @pdpiehowski. Any update on this issue?  Can this issue be closed today or by Tuesday?

**Comment by pdpiehowski** [comment]
An appropriate LC-MS/MS dataset has been identified and acceptance criteria for QA have been established. The searches are now running internally at PNNL to create the benchmark peptide and protein results files for comparison to the metaP pipeline outputs. This will be completed by Tuesday.

**Comment by pdpiehowski** [comment]
We have identified the criteria and created the benchmark dataset to be used for QA of the metaproteomics pipeline. 

All the necessary files and criteria are on the Google Drive.
https://drive.google.com/drive/folders/1ssL5fBYjSH39oX_WnOlB492O-OkYSmf8
