### ISSUE TITLE
Move data defined in .env file to WDL inputs and update processing 

### ISSUE THREAD

**Issue by picowatt** [microbiomedata/metaPro#31]
Prefer passing in data that would otherwise sit in .env file for WDL pipeline. Additionally update processing.

This branch will add new inputs to the WDL pipeline.

**Comment by picowatt** [comment]
Issue blocks #27

**Comment by ssarrafan** [comment]
@picowatt are you planning to finish this issue by Friday?  Is it ok to add it to the next sprint?

**Comment by picowatt** [comment]
@ssarrafan This will be finished by Friday

**Comment by ssarrafan** [comment]
Checked in with @picowatt today and he needs more time to complete. I will move this to the new sprint.

**Comment by ssarrafan** [comment]
@picowatt any update? Can this one be closed yet?
