### ISSUE TITLE
Move Kaiko pipeline to Python 3.9

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaPro#35]
Move Kaiko pipeline to Python 3.9 (latest version of Python supporting tensorflow 1.2.1)

**Comment by ssarrafan** [comment]
Will assign to Camilo when he's in GH, not for current sprint

**Comment by ssarrafan** [comment]
@CamiloPosso any update on this?  Are you actively working on this?

**Comment by CamiloPosso** [comment]
@ssarrafan Yes, I'm working on moving to tensorflow 2.0.0 with python 3.7. Currently the Kaiko pipeline uses tensorflow 1.15.0

**Comment by CamiloPosso** [comment]
Currently on Python 3.10, tensorflow 2.11.0. Using the same model as before. Working on moving this updated version to docker

**Comment by ssarrafan** [comment]
@CamiloPosso thanks for the update. I'll move this to the next sprint for the dockerization unless you'd prefer a new GH issue for that?  Let me know.

**Comment by CamiloPosso** [comment]
Docker image updated and repo moved here: https://github.com/microbiomedata/kaiko_metaproteome
