### ISSUE TITLE
Dockerize Kaiko pipeline

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaPro#36]
Dockerize Kaiko pipeline with ease of use in mind

@pdpiehowski add subtasks here for checkboxes

**Comment by ssarrafan** [comment]
@picowatt please re-assign to Camilo once he's accepted GH invite

**Comment by CamiloPosso** [comment]
[Kaiko_pipeline](https://github.com/CamiloPosso/Kaiko_pipeline) contains the dockerized pipeline, working with python 3.6.

Still have to do:

1) Make shell script to run docker with double click.

**Comment by ssarrafan** [comment]
@CamiloPosso can this issue be closed?

**Comment by ssarrafan** [comment]
Moving to the current sprint per @pdpiehowski report at squad leads meeting

**Comment by CamiloPosso** [comment]
@ssarrafan Yes I think it can be closed, I'm focusing on making unit tests and updating to newer tensorflow and python versions.

The tool is dockerized and has instructions on setting up and using it with Docker: https://github.com/CamiloPosso/Kaiko_pipeline

**Comment by ssarrafan** [comment]
Closing this issue per @CamiloPosso last comment.
