### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaPro#38]
Unit testing to make sure version updates don't break anything else

**Comment by CamiloPosso** [comment]
Is this regarding unit tests for the Kaiko pipeline? If so, I am assigning myself to the issue since I am currently working on this as I update to python 3.9. 

I added 4 such unit tests in this commit: CamiloPosso/Kaiko_pipeline@9d156d36b8d3601be3c2f2308282247461260141

**Comment by ssarrafan** [comment]
@CamiloPosso @picowatt any update on this?  Is this actively being worked on?

**Comment by CamiloPosso** [comment]
@ssarrafan I finished making 4 unit tests with the last commit CamiloPosso/Kaiko_pipeline@522a065b187d15d025c9fb1394f7428fddadbd2a. I can close the issue now.
