### ISSUE TITLE
Integrate schema pkg into WDL pipeline

### ISSUE THREAD

**Issue by picowatt** [microbiomedata/metaPro#41]
Pipeline currently builds Json data products using Mongo and raw python code, integrating schema package removes a dependency on Mongo and ensures data conforms to schema.

TODO replace existing code with schema based code

**Comment by ssarrafan** [comment]
@picowatt I'm going to move this to the next sprint since it was just opened and assuming it won't be done by tomorrow. If it should go in the backlog instead let me know. Thank you!

**Comment by ssarrafan** [comment]
@picowatt @lamccue I will move this to the next sprint.  Lee Ann mentioned that you're still working on the last task of the pipeline related to mongo credentials. Let me know if this can be closed or if it should be moved to the backlog instead.

**Comment by ssarrafan** [comment]
@picowatt assuming this is done?  Please let me know or close the issue if completed. Thanks.
