### ISSUE TITLE
Update Dockerfile and WDL for metadata generation

### ISSUE THREAD

**Issue by picowatt** [microbiomedata/metaPro#47]
Changes to the metadata generation script requires Dockerfile and WDL script updates

TODO
- [x] Update metadata Dockerfile to include new ID minting script
- [x] Incorporate setting client_id and client_secret
- [x] Update WDL script to remove some inputs that have been hardcoded in metadata script

**Comment by ssarrafan** [comment]
@picowatt is this actively being worked on?
