### ISSUE TITLE
Report generation Dockerfile using unsupported parent image

### ISSUE THREAD

**Issue by picowatt** [microbiomedata/metaPro#49]
The report generation script is using python:3.6-stretch is failing during docker build. Debian Stretch has exited LTS and the parent image for the report generation Dockerfile will need to be updated to a newer version of Python. 3.7-buster has been tested and appears to work. 

TODO
- [x] Update report gen Dockerfile to use python:3.7-buster as the parent image
- [x] Validate results generated by new image

**Comment by ssarrafan** [comment]
@picowatt are you actively work on this?

**Comment by picowatt** [comment]
@ssarrafan No I wasn't able to get to it this week. I can move this one and #47 to the next sprint. #48 I'll finish by the end of the day.
