### ISSUE TITLE
Finalize workflow for metaproteomics

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaPro#5]
This issue is to track the following three steps to finalizing the workflow for metaproteomics:
   - Reconfigure architecture
   - Finalize WDL
   - Convert SQL results file to Python

**Comment by anubhav0fnu** [comment]
@ssarrafan , 
- finished `Reconfigure architecture` and `Convert SQL results file to Python`.
- need to move `Finalize WDL` to the next sprint.

FYI(@pdpiehowski)

**Comment by ssarrafan** [comment]
> @ssarrafan ,
> 
> * finished `Reconfigure architecture` and `Convert SQL results file to Python`.
> * need to move `Finalize WDL` to the next sprint.
> 
> FYI(@pdpiehowski)

Thanks @anubhav0fnu. I've created a new issue for the June sprint for you, issue #6
