### ISSUE TITLE
Make config files inputs

### ISSUE THREAD

**Issue by picowatt** [microbiomedata/metaPro#53]
Configuration files for MSGF+ and Masic should be considered inputs to the workflow and be listed in `has_inputs`

TODO
- [x] Update WDL to pass config file information or ID to metadata generation task
- [ ] Update metadata generation script to include relevant information in output metadata

**Comment by ssarrafan** [comment]
@picowatt any update on this issue for this sprint?  Is this still being actively worked on? 
@pdpiehowski should this be in the next sprint?

**Comment by picowatt** [comment]
@ssarrafan In progress, but won't be done this sprint

**Comment by picowatt** [comment]
@ssarrafan This will be done and merged by the end of the day
