### ISSUE TITLE
Incorrect data_object_type for resultant file

### ISSUE THREAD

**Issue by picowatt** [microbiomedata/metaPro#54]
The metadata generation script looks for filenames to set DataObject's `data_object_type`'s value, the hardcoded filename for the resultant file does not match the actual filename.

TODO
Update metadata generation script to insert correct type value

**Comment by ssarrafan** [comment]
@picowatt have you completed updating the metadata generation script to insert correct type value?  Can this issue be closed?

**Comment by picowatt** [comment]
@ssarrafan This one can be closed

**Comment by ssarrafan** [comment]
@picowatt great. I can close it but if you can add any details to the ticket it would be helpful for future generations. :)
