### ISSUE TITLE
Investigate GFF or GFF-like file Generation for Kaiko

### ISSUE THREAD

**Issue by picowatt** [microbiomedata/metaPro#59]
Kaiko's only output is a FASTA, but an annotations file is needed for the pipeline report generation step. Either an entire .gff file will need to be generated or an intermediate .gff-like file will need to be generated from the Kaiko generated FASTA and a reference DB. If an intermediate .gff-like file is the selected approach, non-Kaiko pipeline runs will need to convert the input .gff to this format and our scripts will need to handle this.

TODO
- [x] Investigate which of these solutions will work best and determine implementation details

**Comment by ssarrafan** [comment]
@picowatt still active?

**Comment by ssarrafan** [comment]
@picowatt  will move this one more time but would be great to get an update on if it's active or not.  I'll assume it's going in the backlog if it's still open at the end of this sprint.
