### ISSUE TITLE
Finalize workflow for metaproteomics v2

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaPro#6]
Finalize WDL

**Comment by ssarrafan** [comment]
This issues is related and the final part of issue #5 from the May sprint.

**Comment by ssarrafan** [comment]
@anubhav0fnu and @pdpiehowski I don't see any updates on this issue so I'm adding the backlog label so it can be reprioritized.  Let me know if it's done and shovel be closed.

**Comment by anubhav0fnu** [comment]
> @anubhav0fnu and @pdpiehowski I don't see any updates on this issue so I'm adding the backlog label so it can be reprioritized. Let me know if it's done and shovel be closed.

@ssarrafan, I updated the codebase, added the 
- report(peptide, protein, qc_metric) generation code to it
- restructured the workflow 

Things, I'm currently working on and would like to move to the next sprint
- I'm testing the improvements with a few dry runs on our dataset(stegen). Workflow components work individually fine but running them together is something I'm currently working on especially after adding the report generation code.
- regarding writing a Cromwell-WDL, I'm still figuring out a way to execute commands for multiple containers. 
- Working on metaproteomics-v2 README.
- adding test data.( large(still a topic of discussion) & small(uploaded to [NMDC google drive](https://github.com/microbiomedata/metaPro/issues/7)))

**Comment by anubhav0fnu** [comment]
@ssarrafan @pdpiehowski , I rolled out the v2.
