### ISSUE TITLE
Update README.md 

### ISSUE THREAD

**Issue by picowatt** [microbiomedata/metaPro#68]
The current README is out of date and heavily references the Python pipeline. The WDL pipeline, including the integration of Kaiko, will need to be documented.

- [ ] Update the README.md and other documentation to more accurately describe the current WDL pipeline

**Comment by picowatt** [comment]
In progress, will be completed next sprint.

**Comment by ssarrafan** [comment]
Moving to next sprint per note from @picowatt

**Comment by ssarrafan** [comment]
@picowatt any update on this one?
