### ISSUE TITLE
Add example data and example run command

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/metaPro#7]
Add example data for testing and example of data binding integration from data directory.

**Comment by Michal-Babins** [comment]
Also add outfacing ReadME for metaPro.

**Comment by anubhav0fnu** [comment]
> ata for testing and example of data

@Michal-Babins, 
- I tried to add a small data in the repo with git lfs but, facing issues with the size of the raw file. So, I upload them on the [NMDC google drive](https://drive.google.com/drive/folders/1NYY2mMCy1k5H3BKCrVygB-NnREYVi7p1?usp=sharing). Let me know if you could it access it?
   -  Also, let me know if you would like to get the [test dataset transferred to you facility](https://transfer.lanl.gov/)

- [Readme to run metaproteomics v1](https://hub.docker.com/r/microbiomedata/mepro)
- working on metaproteomics v2 README.

**Comment by Michal-Babins** [comment]
@anubhav0fnu 

Requested Access for NDMC google drive. Thanks.

**Comment by anubhav0fnu** [comment]
@Michal-Babins, added the readme and v2 of the workflow. Please test at your end.

**Comment by anubhav0fnu** [comment]
@Michal-Babins , download data files from [here](https://drive.google.com/file/d/14_rfyU9-Cc5ik6uKbfsnX7jWIKDE5lWk/view?usp=sharing)[publicaly available.] and discard older files from the NMDC drive link.
